Split stage0 due to chroot

diff --git a/modules/hosts/arch-vm/bootstrap-stage0 b/modules/hosts/arch-vm/bootstrap-stage0
--- a/modules/hosts/arch-vm/bootstrap-stage0
+++ b/modules/hosts/arch-vm/bootstrap-stage0
@@ -1,10 +1,18 @@
 #!/bin/sh
 
+# Exit on any error
+set -e
+
 # ------------------------------------------
 # Check the environment
 
 [ -f /sys/firmware/efi/fw_platform_size ] || { echo "error: EFI not enabled" >&2; exit 1; }
+
 ping -c1 -W1 1.1.1.1 >/dev/null 2>&1 ||  { echo "error: no internet" >&2; exit 1; }
+
+stage1="$(command -v -- "$0")"
+stage1="${stage1%0}1"
+[ -f "${stage1}" ] || { echo "error: script must run from repo root" >&2; exit 1; }
 
 # ------------------------------------------
 # Start installation
@@ -34,70 +42,11 @@ pacstrap -K /mnt base base-devel linux linux-firmware sudo git neovim networkman
 # Generate filesystem table
 genfstab -U /mnt >> /mnt/etc/fstab
 
-# Enter installation environment
-arch-chroot /mnt
+# Run bootstrap-stage1 inside installation environment
+cp "$stage1" /mnt/stage1
+arch-chroot /mnt /stage1
+rm -f /mnt/stage1
 
-# Set time zone
-ln -sf /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime
-
-# Set hardware clock
-hwclock --systohc
-
-# Set region and language formatting
-sed -Ei '
-	s/^#(en_US.UTF-8 UTF-8.*)/\1/;
-' /etc/locale.gen
-locale-gen
-
-# Set locale
-echo "LANG=en_US.UTF-8" > /etc/locale.conf
-
-# Set hostname
-echo "arch-vm" > /etc/hostname
-
-# Create initramfs
-mkinitcpio -P
-
-# Set root password
-passwd
-
-# Configure bootloader
-mkdir -p /boot/loader/entries
-cat << EOF > /boot/loader/loader.conf
-timeout 5
-default arch
-EOF
-UUID=$(blkid | sed -nE 's/.*sda2.* PARTUUID="(.*)"/\1/p')
-cat << EOF > /boot/loader/entries/arch.conf
-title Arch Linux
-linux /vmlinuz-linux
-initrd /initramfs-linux.img
-options root=PARTUUID=$UUID rw
-EOF
-bootctl install
-
-# Enable networking
-ln -sf /dev/null /etc/systemd/network/99-default.link
-systemctl enable NetworkManager
-
-# Enable SSD trim
-systemctl enable fstrim.timer
-
-# Allow sudo via password
-sed -Ei '
-	s/^# (%wheel ALL=\(ALL:ALL\) ALL)/\1/;
-' /etc/sudoers
-
-# Add user account
-useradd -m -G wheel -s /bin/bash rick
-passwd rick
-
-# Enable pacman colors
-sed -Ei '
-	s/^#(Color)/\1/;
-' /etc/pacman.conf
-
-# Exit
-exit
+# Reboot
 umount -R /mnt
 reboot
